### ISSUE TITLE
Trigger 流水线组件基础实现（@artusjs/pipeline）

### ISSUE THREAD

**Issue by noahziheng** [artusjs/pipeline#1]

**Comment by hyj1991** [comment]
#2

**Comment by fengmk2** [comment]
@noahziheng @hyj1991 issues 是否考虑集中管理？

**Comment by noahziheng** [comment]
@fengmk2 现在就是集中管理的
https://github.com/orgs/artusjs/projects/2/views/1

**Comment by hyj1991** [comment]
> @fengmk2 现在就是集中管理的 https://github.com/orgs/artusjs/projects/2/views/1

这个看着不错，官方的需求管理看板，以前还没用过
